#+TITLE: Word Processing Versus Text Editing In 2018

*** DONE Prepare Draft
*** TODO Proof Read [in progress <2018-05-07 Mon>] 
*** TODO Add Images [not started]
*** TODO Brainstorm 30 more titles [not started]
*** TODO Publish [not started]

* Word Processing v Text Editing 

** Everything they didn't teach about writing in school

   This is an examination of writing tools rather than a discussion the kinds of writing commonly used or career oriented writing tactics.

   What is the point of that?

   I have found the tools I choose define the problems I face and how I think about solving them.  Perhaps more than the skills I have or the specific challenges I attempt.

   And make no mistake writing and editing are central challenges to the human experience.  Everyone everyone needs the written word. Students, teachers, professionals, small business owners, managers, organizations, teams, parents, friends...  

   Humans use words to communicate.  Those words often need writing down.  

   Before computers the chore of writing, editing, and sharing words was so labor intensive and difficult it is beyond today's imagination. 

** Working Like Win 1995 

   Software tools like Microsoft Word or Google Docs made it much easier for than using modal editors.  Editors made it much easier than the analog typewriter.  The typewriter, a pen and paper. 

   But, it doesn't matter what lifestyle post you've read about hipster typesetting.

   If you have used a mechanical typewriter, you know fiddling with a word processor is **WAY** better than the alternative.

   The mechanical typewriter alternative is includes keeping track of all your margins and line spacing as you type.

   Plus, issues like key jams and ribbon replacements made touch typing a professional field.  If you think printer jams and ink carterage replacements are difficult, imagine having unjam the hammers on a piano whenever you hit the wrong combination of notes.  Or having to replace a ribbon *that was dipped in ink*.

   Professional secretaries often typed 100+ words per minute *because they had to*.  Why?  A single change might require retyping *the entire page*.

   Messy.  That is reality of yesterday.

   On the other hand, word processessors such as Microsoft Word, Apple Pages, LibreOffice, and Google Docs are amazing for a narrow set of uses.

   Need to typing up a 5 paragraph essay?  Even a 5 to 10 page document, you ask?  A standard interoffice communications, proposals, or legal paperwork, by chance?

   Word processessors are designed for this.

   But, have ever had to type a 30+ page paper? Or needed to insert charts?  Or had to use special symbols like legal trademarks or mathmatics notation?

   Rich text formatting editors like MS Word fall short very quickly as those pages and special needs come up.

   One solution files and using extensions or special inserts. But, that falls short quickly when you need to compile documents into a final result.

   Those approaches are not great if you are writing a book, a long form article, academic journal, or legal brief.

   And if you are writing for the web?

   Forget it, the web is not Rich Text compatible.

** Writing Confessions From 2008

   Are you wealthy enough to write a blog post on a legal pad and have it developed by your staff programmer?

   Ever painstakingly format a handout only to find that it looks like garbage in the exported HTML or PDF?

   If you are considering a journalism, copyediting, book writing, or blogging project... Word processing won't cut it.

   Clearly there is a missing tool.

   Enter text editors, omni editors, and integrated development environments. /Stage Left/

   Windows has Notepad.  Mac has TextEdit.  Everything else has Vi.

   Never heard of Vi?  Prepare your body for the rabbit hole.

   Notepad and TextEdit are plain text editors which support a graphical user interface.  Both respond to commands from the keyboard and a mouse.

   Vi and Vi iMporved (ViM) are shell or terminal based text editors.  These only work in your computer's command line.  And only support commands from the keyboard.

   Any and all of these are great for quickly editing some file.  Not immediately useful for larger, more complex project.

   And while ViM is very customizable, it has an extremely difficult learning curve.

   Enter integrated development environments and extendable text editors. 

   These include proprietary / freemium ones like Eclipse, Visual Studio, and Sublime Text.  And open source ones like Atom, VS Code, and the venerable GNU Emacs.  Finally, are also advanced tools like OmniWriter and Scrivener which use their own specialized approach.

   Any of will solve all your tactical problems related to writing stuff.  It will cost you a steep learning curve.

   But, the reward is an ability to publish and share your thoughts with a wider audience.

   So how do you choose?

** Some reccomendations

   I have tried everything.  I'm talking about hours of my free time spent looking at **AMAZING NEW TOOLS** and **MASTERING THE CLASSICS** and **HACKING YOUR WORKFLOW**.

   I have beta access to **HOT NEW PRODUCT**.  And I have **CUSTOMIZED A VIMRC**.

   While I don't know a perfect solution, I can make some reccomendations based on 20+ years of mistakes.

*** Best for small projects
    *Google Docs + Addons*
    Pros Freemium, Extendable, Unlimited cloud storage in Docs Format, Easy to share and publish
    Cons Limited features, Difficult to find/read documentation due to many past releases

*** Best option for a novice 
    *VS Code + Extensions*
    Pros Free, Supports markup, Easy to add features, Easy to find/read documentation
    Cons Extensions cause lag, Higher learning curve than word processors

*** Best poweruser option
    *Spacemacs + Orgmode*
    Pros Too numerous to mention
    Cons Hard to get started (more of a fun challenge IMHO)



