#+TITLE: Full Stack React Course
#+STARTUP: indent
#+STARTUP: overview
* Part One: Full Stack React Overview
[[https://docs.google.com/document/d/1ZVLphlOH0PEOUCd5v2UJVHiRSKuYjJI-AS4xQWYXmq8/edit#heading=h.fnjk6vnqzbqk][Course Cheat Sheet]]
** Project Overview
This is one single project with a large number of features.  The first part will build in a survey function that will allow the app owner to:
*** App Goals
1. Ask some number of users to answer questions.
2. Send an email requesting feedback.
3. Record their answers.
4. Get a tabulation of results.
*** App Work Flow: 
One: Mongodb PassportJS Stripe React Redux Redux Form
User signs up via OAuth -> Pays via Stripe -> Creates a new campaign -> Enters email list to send survey ->

Two: Email-provider Express Mongodb
Send email list of survey takers -> Survey takers click email link to provide feedback ->

Three: Mongodb React Redux
We tabulate feedback -> Use receives report of all survey responses
*** [[https://www.udemy.com/node-with-react-fullstack-web-development/learn/v4/t/lecture/7593662?start=0][Course Link: App Mockups]]
* Server Side Architecture
This app will use Node and Express deployed to Heroku.
